orbs:
  codecov: codecov/codecov@1.0.4
version: 2.1
jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: cypress/base:12.1.0
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "package.json" }}
            - run:
                  name: install dependencies
                  command: yarn install
            - save_cache:
                  key: dependency-cache-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: test
                  command: yarn test:coverage
            - codecov/upload:
                  file: coverage/*.json
            - run:
                  name: e2e
                  command: yarn e2e:run
            - run:
                  name: build
                  command: yarn build
            - run:
                  name: deploy
                  command: yarn deploy
