orbs:
  codecov: codecov/codecov@1.0.4
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.14.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - run:
          name: test
          command: yarn test:coverage
      - codecov/upload:
          file: coverage/*.json
